
local ITEM = items.RegisterClass("Ironite")
ITEM.Icon = "darkland/rpg/items/ironite"
ITEM.GatherTime = 15
ITEM.HolderModel = "models/props_wasteland/rockcliff01c.mdl"
ITEM.HolderColor = Color(191,191,191,255)
ITEM.Weight = 0.1
ITEM.SmeltRate = 1
ITEM.SmeltsTo = {"Ironium"}
ITEM.Category = "Raw Materials"
local ITEM = items.RegisterClass("Tinite")
ITEM.Icon = "darkland/rpg/items/tinite"
ITEM.GatherTime = 15
ITEM.HolderModel = "models/props_wasteland/rockcliff01c.mdl"
ITEM.HolderColor = Color(191,191,191,255)
ITEM.Weight = 0.2
ITEM.SmeltRate = 1
ITEM.SmeltsTo = {"Tinium"}
ITEM.Category = "Raw Materials"
local ITEM = items.RegisterClass("Silverite")
ITEM.Icon = "darkland/rpg/items/silverite"
ITEM.GatherTime = 15
ITEM.HolderModel = "models/props_wasteland/rockcliff01c.mdl"
ITEM.HolderColor = Color(191,191,191,255)
ITEM.Weight = 0.4
ITEM.SmeltRate = 0.7
ITEM.SmeltsTo = {"Silverium"}
ITEM.Category = "Raw Materials"


local ITEM = items.RegisterClass("Goldite")
ITEM.Icon = "darkland/rpg/items/goldite"
ITEM.GatherTime = 15
ITEM.HolderModel = "models/props_wasteland/rockcliff01c.mdl"
ITEM.HolderColor = Color(255,215,0,255)
ITEM.Weight = 0.7
ITEM.SmeltRate = 0.5
ITEM.SmeltsTo = {"Goldium"}
ITEM.Category = "Raw Materials"
local ITEM = items.RegisterClass("Runite")
ITEM.Icon = "darkland/rpg/items/runite"
ITEM.GatherTime = 15
ITEM.HolderModel = "models/props_wasteland/rockcliff01c.mdl"
ITEM.HolderColor = Color(191,191,191,255)
ITEM.Weight = 1
ITEM.SmeltRate = 0.12
ITEM.SmeltsTo = {"Runium"}
ITEM.Category = "Raw Materials"